---
- name: Install OpenSCAP and assess compliance
  hosts: all
  become: true
  tasks:
    - name: Install OpenSCAP tool and security guide
      yum:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present
    - name: Validate installation
      shell: oscap --version | grep "command line tool"
      register: oscap_version
    - name: Show versions
      debug:
        # Use `>` to fold/convert newlines to spaces.
        msg: >
          Running
          {{ ansible_distribution }}
          {{ ansible_distribution_version }}
          {{ oscap_version.stdout }}"
    - name: Scan
      command: >
        oscap xccdf eval
        --profile xccdf_org.ssgproject.content_profile_pci-dss
        --report /vagrant/report.html
        /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml
      ignore_errors: true
      register: oscap_result
    - name: Show results
      debug:
        var: oscap_result.stdout
